stages:
  - test
  - deploy

test-stage:
  image: registry.gitlab.com/schroedinger1/backend:gitlabci
  stage: test
  script:
    - service elasticsearch start
    - service postgresql start

    - npm install --silent
    - npm run index-test
    - npm run migrate-test
    - npm run test-test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  services:
    - name: redis:6.0.6-alpine
      alias: redis
    - name: rabbitmq:3.8.8-management
      alias: rabbitmq
  variables:
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: averysecuredpassword

    POSTGRES_HOST: localhost
    POSTGRES_DB: schroedinger
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    ACCESS_LOG_LEVEL: error
    DEBUG_LOG_LEVEL: debug
    PORT: 3000
    REDIS_HOST: redis
    ELASTIC_HOST: localhost:9200
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_USER: admin
    RABBITMQ_PASSWORD: averysecuredpassword
    MAIL_PASSWORD: averysecuredpassword
    MAIL_SENDER: noreply@schroedinger-survey.de
    MAIL_SERVER: smtp.ionos.de
    MAIL_QUEUE: mail-queue
    FRONTEND_URL: schroedinger-survey.de
    TTL: 300
    SECRET: bah23h$(gHHZ9
    BCRYPT_ROUND: 1
    RECAPTCHA_TOKEN: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
  tags:
    - docker

deploy-stage:
  stage: deploy
  script:
    - cd /schroedinger/backend/configurations && git stash && git pull
    - cd /schroedinger/backend && git stash && git pull && docker-compose up -d --build
  only:
    - master
  tags:
    - shell
