image: node:14.8.0-stretch

services:
  - postgres:12.4-alpine
  - redis:6.0.6-alpine

variables:
  POSTGRES_DB: schroedinger
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  untracked: true
  key: backend_node_modules
  paths:
  - node_modules/


stages:
  - test
  - deploy

test-stage:
  stage: test
  script:
    - echo "$BACKEND_DOT_ENV_TEST" >> .env.test
    - npm config set cache /cache/backend_node_modules --global
    - npm install
    - npm run lint
    - npm run migrate-test
    - npm run test-test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

deploy-stage:
  stage: deploy
  script:
    - cd /schroedinger/$CI_PROJECT_NAME && git stash && git pull && echo \"$BACKEND_DOT_ENV_PRODUCTION\" >> .env && docker-compose up -d --build && sleep 10 && curl --silent --show-error --fail http://localhost:3000/health --retry 5 --retry-delay 5 --retry-connrefused"
  only:
    - master
