stages:
  - test
  - deploy

test-stage:
  image: node:14.8.0-stretch
  stage: test

  script:
    - mv .env.example .env.test
    - npm config set cache /cache/backend_node_modules --global
    - npm install
    # - npm run lint
    - npm run migrate-test
    - npm run test-test

  coverage: /All\sfiles.*?\s+(\d+.\d+)/

  services:
  - postgres:12.4-alpine
  - redis:6.0.6-alpine
  - name: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    alias: elasticsearch
    command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]




  variables:
    POSTGRES_DB: schroedinger
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust


  cache:
    untracked: true
    key: schroedinger_backend_node_modules
    paths:
    - node_modules/
  tags:
    - docker

deploy-stage:
  stage: deploy
  script:
    - cd /schroedinger/backend
    - git stash
    - git pull
    - echo "$DOT_ENV" >> .env
    - docker-compose up -d --build
    - sleep 10
    - curl --silent --show-error --fail http://localhost:3000/health --retry 5 --retry-delay 5 --retry-connrefused
  only:
    - master
  tags:
    - shell
