image: node:alpine

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: schroedinger
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - test

setup-test-env:
  stage: setup
  script:
    - npm install
    - npm run lint
    - npm run migrate-test
    - npm run test-test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/