stages:
  - lint
  - test

lint-backend:
  image: node:alpine
  stage: lint
  script:
    - npm install
    - npm run lint

test-backend:
  image: node:alpine
  stage: test
  script:
    - npm install
    - npm run test