image: node:14.8.0-stretch

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: schroedinger
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
  - deploy

test-stage:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run migrate-test
    - npm run test-test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

deploy-stage:
  stage: deploy
  script:
    - apt-get update -qq
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $USER_AND_HOST "cd $CI_PROJECT_NAME && git stash && git pull && export printf '$BACKEND_DOT_ENV' && docker-compose up -d --build"
  only:
    - master