version: "3.7"

services:
  schroedinger-database:
    restart: always
    container_name: schroedinger-database
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - schroedinger-database-data:/var/lib/postgresql/data/

  schroedinger-backend:
    build: .
    restart: always
    container_name: schroedinger-backend
    ports:
      - 3000:3000
    depends_on:
      - schroedinger-database
    links:
      - schroedinger-database

volumes:
  schroedinger-database-data: