version: "3.7"

services:
  schroedinger-backend:
    build: .
    restart: unless-stopped
    container_name: schroedinger-backend
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - schroedinger-postgresql
      - schroedinger-redis
      - schroedinger-elasticsearch
      - schroedinger-rabbitmq
      - schroedinger-mongo
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - /bin/bash
      - -c
      - |
        npm run index-prod
        npm run migrate-prod
        npm run server-prod
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:3000/health"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-worker:
    build: .
    restart: unless-stopped
    container_name: schroedinger-worker
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - schroedinger-postgresql
      - schroedinger-redis
      - schroedinger-elasticsearch
      - schroedinger-rabbitmq
      - schroedinger-backend
      - schroedinger-mongo
    command:
      - /bin/bash
      - -c
      - |
        npm run worker-prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3002/health" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-rabbitmq:
    restart: unless-stopped
    container_name: schroedinger-rabbitmq
    hostname: schroedinger-rabbitmq
    build: ./docker/rabbitmq
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    ports:
      - 15672:15672
    volumes:
      - schroedinger-rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@schroedinger-rabbitmq
      - ./configurations/rabbitmq-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json:ro
      - ./configurations/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-postgresql:
    restart: unless-stopped
    container_name: schroedinger-postgresql
    image: postgres:12.4-alpine
    command: postgres -c config_file=/tmp/postgresql.conf
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    volumes:
      - schroedinger-postgresql-data:/var/lib/postgresql/data/
      - ./configurations/postgresql.conf:/tmp/postgresql.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-pgadmin4:
    restart: unless-stopped
    container_name: schroedinger-pgadmin4
    build: ./docker/pgadmin4
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - schroedinger-pgadmin4-data:/var/lib/pgadmin
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - schroedinger-postgresql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login?next=%2F" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-redis:
    restart: unless-stopped
    container_name: schroedinger-redis
    image: redis:6.0.6-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    volumes:
      - schroedinger-redis-data:/data
      - ./configurations/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-redis-commander:
    container_name: schroedinger-redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    ports:
      - "8081:3000"
    depends_on:
      - schroedinger-redis
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "/redis-commander/bin/healthcheck.js"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-mongo:
    container_name: schroedinger-mongo
    image: mongo:3.6.20-xenial
    restart: unless-stopped
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    volumes:
      - schroedinger-mongo-data:/data
      - ./configurations/mongod.conf:/etc/mongod.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-mongoclient:
    container_name: schroedinger-mongoclient
    image: mongoclient/mongoclient:4.0.0
    restart: unless-stopped
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    ports:
      - 3003:3000
    depends_on:
      - schroedinger-mongo
    volumes:
      - schroedinger-mongoclient-data:/data/db/mongoclient/mongoclient
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/mongoclient"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-elasticsearch:
    restart: unless-stopped
    container_name: schroedinger-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    volumes:
      - schroedinger-elasticsearch-data:/usr/share/elasticsearch/data
      - ./configurations/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health", "-u", "$ELASTIC_USERNAME:$ELASTIC_PASSWORD"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-kibana:
    restart: unless-stopped
    container_name: schroedinger-kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    ports:
      - 5601:5601
    depends_on:
      - schroedinger-elasticsearch
    volumes:
      - ./configurations/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "curl", "f", "http://localhost:5601/app/home" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-metricbeat:
    restart: unless-stopped
    container_name: schroedinger-metricbeat
    image: docker.elastic.co/beats/metricbeat:7.9.1
    user: root
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
    volumes:
      - ./configurations/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
    depends_on:
      - schroedinger-elasticsearch
      - schroedinger-backend
      - schroedinger-redis
      - schroedinger-rabbitmq
      - schroedinger-pgadmin4
      - schroedinger-postgresql
      - schroedinger-worker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5066"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-backup:
    container_name: schroedinger-backup
    image: futurice/docker-volume-backup:2.0.0
    restart: on-failure
    env_file:
      - .env
    volumes:
      - schroedinger-mongo-data:/backup/schroedinger-mongo-data:ro
      - schroedinger-mongoclient-data:/backup/schroedinger-mongoclient-data:ro
      - schroedinger-postgresql-data:/backup/schroedinger-postgresql-data:ro
      - schroedinger-pgadmin4-data:/backup/schroedinger-pgadmin4-data:ro
      - schroedinger-redis-data:/backup/schroedinger-redis-data:ro
      - schroedinger-rabbitmq-data:/backup/schroedinger-rabbitmq-data:ro
      - schroedinger-elasticsearch-data:/backup/schroedinger-elasticsearch-data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  schroedinger-mongo-data:
  schroedinger-mongoclient-data:
  schroedinger-postgresql-data:
  schroedinger-pgadmin4-data:
  schroedinger-redis-data:
  schroedinger-rabbitmq-data:
  schroedinger-elasticsearch-data:
