version: "3.7"

services:
  schroedinger-backend:
    build: .
    restart: always
    container_name: schroedinger-backend
    ports:
      - 3000:3000
    depends_on:
      - schroedinger-postgresql
      - schroedinger-redis
      - schroedinger-elasticsearch
      - schroedinger-rabbitmq
    command:
      - /bin/bash
      - -c
      - |
        npm run index-prod
        npm run migrate-prod
        npm run server-prod
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:3000/health"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-worker:
    build: .
    restart: always
    container_name: schroedinger-worker
    depends_on:
      - schroedinger-postgresql
      - schroedinger-redis
      - schroedinger-elasticsearch
      - schroedinger-rabbitmq
      - schroedinger-backend
    command:
      - /bin/bash
      - -c
      - |
        npm run worker-prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3002/health" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-rabbitmq:
    restart: always
    container_name: schroedinger-rabbitmq
    hostname: schroedinger-rabbitmq
    build: ./docker/rabbitmq
    ports:
      - 15672:15672
    volumes:
      - schroedinger-rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@schroedinger-rabbitmq
      - ./conf/rabbitmq-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json:ro
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-postgresql:
    restart: always
    container_name: schroedinger-postgresql
    image: postgres:12.4-alpine
    command: postgres -c config_file=/tmp/postgresql.conf
    env_file:
      - .env
    volumes:
      - schroedinger-postgresql-data:/var/lib/postgresql/data/
      - ./conf/postgresql.conf:/tmp/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-pgadmin4:
    restart: always
    container_name: schroedinger-pgadmin4
    build: ./docker/pgadmin4
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - schroedinger-pgadmin4-data:/var/lib/pgadmin
    depends_on:
      - schroedinger-postgresql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login?next=%2F" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-redis:
    restart: always
    container_name: schroedinger-redis
    image: redis:6.0.6-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - schroedinger-redis-data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-elasticsearch:
    restart: always
    container_name: schroedinger-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    env_file:
      - .env
    volumes:
      - schroedinger-elasticsearch-data:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-kibana:
    restart: always
    container_name: schroedinger-kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    env_file:
      - .env
    ports:
      - 5601:5601
    depends_on:
      - schroedinger-elasticsearch
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    healthcheck:
      test: [ "CMD", "curl", "f", "http://localhost:5601/app/home" ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s


  schroedinger-metricbeat:
    restart: always
    container_name: schroedinger-metricbeat
    image: docker.elastic.co/beats/metricbeat:7.9.1
    user: root
    volumes:
      - ./conf/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
    depends_on:
      - schroedinger-elasticsearch
      - schroedinger-backend
      - schroedinger-redis
      - schroedinger-rabbitmq
      - schroedinger-pgadmin4
      - schroedinger-postgresql
      - schroedinger-worker

volumes:
  schroedinger-postgresql-data:
  schroedinger-pgadmin4-data:
  schroedinger-redis-data:
  schroedinger-rabbitmq-data:
  schroedinger-elasticsearch-data:
