version: "3.7"

services:
  schroedinger-database:
    restart: always
    container_name: schroedinger-database
    image: postgres:12.4-alpine
    env_file:
      - .env
    volumes:
      - schroedinger-database-data:/var/lib/postgresql/data/

  schroedinger-backend:
    build: .
    restart: always
    container_name: schroedinger-backend
    ports:
      - 3000:3000
    depends_on:
      - schroedinger-database
    links:
      - schroedinger-database
    volumes:
      - schroedinger_backend_node_modules:/app/node_modules

  schroedinger-redis:
    restart: always
    container_name: schroedinger-redis
    image: redis:6.0.6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - schroedinger-redis-data:/data

volumes:
  schroedinger-database-data:
  schroedinger_backend_node_modules:
  schroedinger-redis-data: