version: "3"

services:
  database:
    restart: always
    container_name: schroedinger-database
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/

  backend:
    build: .
    restart: always
    container_name: schroedinger-backend
    ports:
      - 3000:3000
    depends_on:
      - database

volumes:
  database-data: