CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

ALTER TABLE IF EXISTS surveys
    ALTER COLUMN start_date SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN end_date SET DEFAULT null;

ALTER TABLE IF EXISTS users
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_changed_password SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS surveys
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS tokens
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS constrained_questions
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS constrained_questions_options
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS freestyle_questions
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS submissions
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS freestyle_answers
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS constrained_answers
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS reset_password_tokens
    ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_edited SET DEFAULT CURRENT_TIMESTAMP;
